apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongodb-persitent-storage
          mountPath: /data/db
  volumes:
    - name: mongodb-persitent-storage
      persistentVolumeClaim:
        claimName: mongodb-pvc